version: '3.8'

services:
  database:
    image: postgres:15
    container_name: blog-db
    environment:
      POSTGRES_DB: blog       # Database name
      POSTGRES_USER: postgres  # Username
      POSTGRES_PASSWORD: password  # Password
      PGDATA: /var/lib/postgresql/data/pgdata  # Custom location for PostgreSQL data
    ports:
      - "5432:5432"            # Maps container's 5432 to host's 5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    network_mode: "bridge"      # Ensures localhost access from outside Docker

volumes:
  pgdata:
    driver: local
